# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SCHEME: MountainViewUI
  TEST_DEVICE: platform=iOS Simulator,name=Iphone 11,OS=16.4

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Build
      shell: bash
      run: xcodebuild -scheme '${{ env.SCHEME }}' -sdk iphonesimulator -destination '${{ env.TEST_DEVICE }}' build
     # run: swift build -v
    - name: Run tests
      shell: bash
      run: xcodebuild -scheme '${{ env.SCHEME }}' -sdk iphonesimulator -destination '${{ env.TEST_DEVICE }}' test
      # run: swift test -v
